on:
  push:
    branches:
      - **
  pull_request:
    branches:
      - **

jobs:
  buidJoB:
    name: buid
    runs-on: macos-13
    steps:
      - uses: actions/checkout@main
        with:
          submodules: 'true'
      - name: Set up Xcode
        run: |
          sudo xcode-select -s /Applications/Xcode_15.0.app/Contents/Developer
          xcode-select -p
          xcodebuild -version
      - name: Build
        run: |
          cd Demo
          pod install
          swift build -v
          xcodebuild -workspace Demo.xcworkspace -scheme macOS
          xcodebuild -workspace Demo.xcworkspace -scheme iOS -sdk iphonesimulator
          # xcodebuild -workspace Demo.xcworkspace -scheme tvOS -sdk appletvsimulator
          
